CREATE TABLE members (
  id bigint generated by default as identity primary key,
  nick_name text,
  tg_user_name text,
  tg_user_id text,
  tg_user_description text,
  email text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table members enable row level security;

create policy "student are public." on members for
    select using (true);

create policy "Individuals can create members." on members for
     insert with check (true);

create policy "Individuals can update their own members." on members for
    update using (true);

create policy "Individuals can delete their own members." on members for
    delete using (true);


CREATE TABLE polls (
  id bigint generated by default as identity primary key,
  title TEXT NOT NULL,
  options TEXT[] NOT NULL,
  poll_description TEXT,
  is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  allows_multiple_answers BOOLEAN NOT NULL DEFAULT FALSE,
  only_members BOOLEAN NOT NULL DEFAULT FALSE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null

);

alter table polls enable row level security;

create policy "polls are public." on polls for
    select using (true);

create policy "Individuals can create polls." on polls for
     insert with check (true);

create policy "Individuals can update their own polls." on polls for
    update using (true);

create policy "Individuals can delete their own polls." on polls for
    delete using (true);    


CREATE TABLE poll_votes (
  poll_id bigint NOT NULL,
  option TEXT NOT NULL,
  tg_user_id TEXT NOT NULL,
  FOREIGN KEY (poll_id) REFERENCES polls (id)
);    

alter table poll_votes enable row level security;

create policy "poll_votes are public." on poll_votes for
    select using (true);

create policy "Individuals can create poll_votes." on poll_votes for
     insert with check (true);

create policy "Individuals can update their own poll_votes." on poll_votes for
    update using (true);

create policy "Individuals can delete their own poll_votes." on poll_votes for
    delete using (true);    
